server:
  port: 8396
  servlet:
    context-path: /ucsalAPIRestEstacionamento
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - '*'
info:
  tags:
    environment: Estacionamento
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true 
  application:
    name: ucsalAPIRestEstacionamento
  jpa:
    properties:
      hibernate: 
        jdbc: 
          lob: 
           non_contextual_creation: false
    show-sql: true
    generate-ddl: true
  hibernate:
     ddl-auto: update
     database: postgresql
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     open-in-view: false
     generate-ddl: true
         
  datasource:
   driver-class-name: org.postgresql.Driver
   #username: postgres
   #password: admin
   url: postgres://zuohpkuyqqkghu:43444de19c72eb6f79e0eab7ffc921b2a8590a57deb96e44bc249bbb9bb38c57@ec2-3-234-131-8.compute-1.amazonaws.com:5432/d685ktr8cqmaop
   #url: jdbc:postgresql://localhost:5432/estacionamento
   platform: postgres
   initialization-mode: always
   continue-on-error: true
    
# Logger configuration
#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: info
#    org.hibernate: debug
   
